-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 18:43:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userinfo` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `gender` TINYINT(1) NULL,
  `age` INT NULL,
  `email` VARCHAR(45) NULL,
  `bio` VARCHAR(120) NULL,
  `tel` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `register_date` DATETIME NULL,
  `activate` TINYINT(2) NULL COMMENT '帐号活跃状态。\n0.未激活\n1. 激活',
  `city` INT NULL COMMENT '用户所在城市',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resource_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resource_type` (
  `type_id` INT NOT NULL,
  `detail` VARCHAR(45) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resource_index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resource_index` (
  `resource_id` INT NOT NULL,
  `type_id` INT NULL,
  `objectid` VARCHAR(45) NULL,
  `resource_indexcol` VARCHAR(45) NULL,
  PRIMARY KEY (`resource_id`),
  INDEX `type_id_idx` (`type_id` ASC),
  CONSTRAINT `type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`resource_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `login_time` DATETIME NULL COMMENT '登录的时间',
  `ip` VARCHAR(45) NULL COMMENT '登录的IP地址',
  `mac` VARCHAR(45) NULL COMMENT '设备的mac地址。',
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userinfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`critics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`critics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `resource_id` INT NULL,
  `critics` INT NULL COMMENT '用户对某物品的评价\n暂时分为\n1.好评\n0.无评价\n-1.差评。；‘\n',
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `resource_id_idx` (`resource_id` ASC),userinfouserinfouserinfouserinfo
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userinfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`resource_id`)
    REFERENCES `mydb`.`resource_index` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
